//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var nib: nib { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func nib(bundle: Foundation.Bundle) -> nib {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
    try self.nib.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var home: home { .init(source: .init(bundle: bundle, tableName: "Home", preferredLanguages: preferredLanguages, locale: locale)) }

    func home(preferredLanguages: [String]) -> home {
      .init(source: .init(bundle: bundle, tableName: "Home", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.home` struct is generated, and contains static references to 1 localization keys.
    struct home {
      let source: RswiftResources.StringResource.Source

      /// Value: Home1
      ///
      /// Key: title
      var title: RswiftResources.StringResource { .init(key: "title", tableName: "Home", source: source, developmentValue: nil, comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 9 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `main.disable`.
    var mainDisable: RswiftResources.ColorResource { .init(name: "main.disable", path: [], bundle: bundle) }

    /// Color `main.input.bg`.
    var mainInputBg: RswiftResources.ColorResource { .init(name: "main.input.bg", path: [], bundle: bundle) }

    /// Color `main.input.text`.
    var mainInputText: RswiftResources.ColorResource { .init(name: "main.input.text", path: [], bundle: bundle) }

    /// Color `mainBg`.
    var mainBg: RswiftResources.ColorResource { .init(name: "mainBg", path: [], bundle: bundle) }

    /// Color `mainOrange`.
    var mainOrange: RswiftResources.ColorResource { .init(name: "mainOrange", path: [], bundle: bundle) }

    /// Color `mainText`.
    var mainText: RswiftResources.ColorResource { .init(name: "mainText", path: [], bundle: bundle) }

    /// Color `opacityBg`.
    var opacityBg: RswiftResources.ColorResource { .init(name: "opacityBg", path: [], bundle: bundle) }

    /// Color `placeholder`.
    var placeholder: RswiftResources.ColorResource { .init(name: "placeholder", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 9 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `ico.tabbar.genres`.
    var icoTabbarGenres: RswiftResources.ImageResource { .init(name: "ico.tabbar.genres", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ico.tabbar.home`.
    var icoTabbarHome: RswiftResources.ImageResource { .init(name: "ico.tabbar.home", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ico.tabbar.news`.
    var icoTabbarNews: RswiftResources.ImageResource { .init(name: "ico.tabbar.news", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ico.tabbar.profile`.
    var icoTabbarProfile: RswiftResources.ImageResource { .init(name: "ico.tabbar.profile", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.hidden.password`.
    var iconHiddenPassword: RswiftResources.ImageResource { .init(name: "icon.hidden.password", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.show.password`.
    var iconShowPassword: RswiftResources.ImageResource { .init(name: "icon.show.password", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icons8-back-64-2 1`.
    var icons8Back6421: RswiftResources.ImageResource { .init(name: "icons8-back-64-2 1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icons8-email-100 1`.
    var icons8Email1001: RswiftResources.ImageResource { .init(name: "icons8-email-100 1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img.login.bg`.
    var imgLoginBg: RswiftResources.ImageResource { .init(name: "img.login.bg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
          }
        }
      }
    }
  }

  /// This `_R.font` struct is generated, and contains static references to 9 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `Inter-Black`.
    var interBlack: RswiftResources.FontResource { .init(name: "Inter-Black", bundle: bundle, filename: "Inter-Black.ttf") }

    /// Font `Inter-Bold`.
    var interBold: RswiftResources.FontResource { .init(name: "Inter-Bold", bundle: bundle, filename: "Inter-Bold.ttf") }

    /// Font `Inter-ExtraBold`.
    var interExtraBold: RswiftResources.FontResource { .init(name: "Inter-ExtraBold", bundle: bundle, filename: "Inter-ExtraBold.ttf") }

    /// Font `Inter-ExtraLight`.
    var interExtraLight: RswiftResources.FontResource { .init(name: "Inter-ExtraLight", bundle: bundle, filename: "Inter-ExtraLight.ttf") }

    /// Font `Inter-Light`.
    var interLight: RswiftResources.FontResource { .init(name: "Inter-Light", bundle: bundle, filename: "Inter-Light.ttf") }

    /// Font `Inter-Medium`.
    var interMedium: RswiftResources.FontResource { .init(name: "Inter-Medium", bundle: bundle, filename: "Inter-Medium.ttf") }

    /// Font `Inter-Regular`.
    var interRegular: RswiftResources.FontResource { .init(name: "Inter-Regular", bundle: bundle, filename: "Inter-Regular.ttf") }

    /// Font `Inter-SemiBold`.
    var interSemiBold: RswiftResources.FontResource { .init(name: "Inter-SemiBold", bundle: bundle, filename: "Inter-SemiBold.ttf") }

    /// Font `Inter-Thin`.
    var interThin: RswiftResources.FontResource { .init(name: "Inter-Thin", bundle: bundle, filename: "Inter-Thin.ttf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [interBlack, interBold, interExtraBold, interExtraLight, interLight, interMedium, interRegular, interSemiBold, interThin].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 9 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `Inter-Black.ttf`.
    var interBlackTtf: RswiftResources.FileResource { .init(name: "Inter-Black", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-Bold.ttf`.
    var interBoldTtf: RswiftResources.FileResource { .init(name: "Inter-Bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-ExtraBold.ttf`.
    var interExtraBoldTtf: RswiftResources.FileResource { .init(name: "Inter-ExtraBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-ExtraLight.ttf`.
    var interExtraLightTtf: RswiftResources.FileResource { .init(name: "Inter-ExtraLight", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-Light.ttf`.
    var interLightTtf: RswiftResources.FileResource { .init(name: "Inter-Light", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-Medium.ttf`.
    var interMediumTtf: RswiftResources.FileResource { .init(name: "Inter-Medium", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-Regular.ttf`.
    var interRegularTtf: RswiftResources.FileResource { .init(name: "Inter-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-SemiBold.ttf`.
    var interSemiBoldTtf: RswiftResources.FileResource { .init(name: "Inter-SemiBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-Thin.ttf`.
    var interThinTtf: RswiftResources.FileResource { .init(name: "Inter-Thin", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.nib` struct is generated, and contains static references to 7 nibs.
  struct nib {
    let bundle: Foundation.Bundle

    /// Nib `ForgotViewController`.
    var forgotViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ForgotViewController", bundle: bundle) }

    /// Nib `GenresViewController`.
    var genresViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "GenresViewController", bundle: bundle) }

    /// Nib `HomeViewController`.
    var homeViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "HomeViewController", bundle: bundle) }

    /// Nib `LoginViewController`.
    var loginViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "LoginViewController", bundle: bundle) }

    /// Nib `NewsViewController`.
    var newsViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "NewsViewController", bundle: bundle) }

    /// Nib `ProfileViewController`.
    var profileViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ProfileViewController", bundle: bundle) }

    /// Nib `RegisterViewController`.
    var registerViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "RegisterViewController", bundle: bundle) }

    func validate() throws {
      if UIKit.UIImage(named: "icons8-back-64-2 1", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icons8-back-64-2 1' is used in nib 'ForgotViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icons8-email-100 1", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icons8-email-100 1' is used in nib 'ForgotViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "img.login.bg", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'img.login.bg' is used in nib 'ForgotViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "main.disable", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'main.disable' is used in nib 'ForgotViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "main.input.bg", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'main.input.bg' is used in nib 'ForgotViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "placeholder", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'placeholder' is used in nib 'ForgotViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "mainBg", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'mainBg' is used in nib 'HomeViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "mainText", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'mainText' is used in nib 'HomeViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "img.login.bg", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'img.login.bg' is used in nib 'LoginViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "main.input.bg", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'main.input.bg' is used in nib 'LoginViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "main.input.text", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'main.input.text' is used in nib 'LoginViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "img.login.bg", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'img.login.bg' is used in nib 'RegisterViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "Color", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'Color' is used in nib 'RegisterViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "main.input.bg", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'main.input.bg' is used in nib 'RegisterViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "main.input.text", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'main.input.text' is used in nib 'RegisterViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "mainText", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'mainText' is used in nib 'RegisterViewController', but couldn't be loaded.") }
    }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {

      }
    }
  }
}